---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bjw-s-charts
  namespace: ${dsomm_app_name}
spec:
  interval: 12h
  url: https://bjw-s-labs.github.io/helm-charts/
---
apiVersion: v1
kind: Namespace
metadata:
  name: ${dsomm_app_name}
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dsomm
  namespace: ${dsomm_app_name}
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.1.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: ${dsomm_app_name}
  install:
    remediation:
      retries: 3
  values:
    controllers:
      ${dsomm_app_name}:
        replicas: 1
        annotations:
          reloader.stakater.com/auto: 'true'
        containers:
          app:
            image:
              repository: wurstbrot/dsomm
              tag: 3.11.0
            ports:
              - name: http
                containerPort: &httpPort 8080
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 1Gi
    service:
      app:
        controller: ${dsomm_app_name}
        type: ClusterIP
        ports:
          http:
            port: *httpPort
            protocol: TCP
    ingress:
      app:
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          kubernetes.io/tls-acme: 'true'
          nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
          nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 3Gi
        globalMounts:
          - path: /app