---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-${default_k8s_cert_name}
  namespace: cert-manager
spec:
  secretName: wildcard-${default_k8s_cert_name}
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: 'true'
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: 'true'
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames: ['*.${app_k8s_domain_name}']
