apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ${dashy_app_name}
resources:
  - ./release.yaml
configMapGenerator:
  - name: dashy-configmap
    files:
      - config.yaml=./resources/config.yaml
generatorOptions:
  disableNameSuffixHash: true