---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bjw-s-charts
  namespace: ${dashy_app_name}
spec:
  interval: 12h
  url: https://bjw-s-labs.github.io/helm-charts/
---
apiVersion: v1
kind: Namespace
metadata:
  name: ${dashy_app_name}
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dashy
  namespace: ${dashy_app_name}
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.1.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: ${dashy_app_name}
  install:
    remediation:
      retries: 3
  values:
    controllers:
      ${dashy_app_name}:
        replicas: 2
        annotations:
          reloader.stakater.com/auto: 'true'
        containers:
          app:
            image:
              repository: ghcr.io/lissy93/dashy
              tag: 3.1.0@sha256:e0e4d344f9be6d6f0061bb4f5368efd5034e8f2cec886d8afefc89a76be830d4
            env:
              TZ: Europe/Warsaw
              UID: 1000
              GID: 1000
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities:
                drop: [ALL]
            ports:
              - name: http
                containerPort: &httpPort 8080
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 3Gi
    service:
      app:
        controller: ${dashy_app_name}
        type: ClusterIP
        ports:
          http:
            port: *httpPort
            protocol: TCP
    ingress:
      app:
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          kubernetes.io/tls-acme: 'true'
          nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
          nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    persistence:
      config-file:
        type: configMap
        name: dashy-configmap
        globalMounts:
          - path: /app/user-data/conf.yml
            subPath: config.yaml  # Needs to match configMapGenerator.files in kustomization.yaml
            readOnly: true
