---
apiVersion: v1
kind: Secret
metadata:
  name: aws-s3-secret-netbox
  namespace: netbox
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:aENs9/7OXcjUugHwIrs/S0EGfRA=,iv:l+70NjGwqnb4riFt6bhLtkixDN5Kg0Q2qBnemv0r8mQ=,tag:zDprPOJ7b3FH8UsvB/FJ7Q==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:PgGdEQ3sGC8Ma0IvrXtpRJ177J8xu41OFg7iRONMjzHga3Zd3amALQ==,iv:hRqAsAVI6jI2r1wFTBWpImJgtm5xxP+YzQswQCxBO6o=,tag:5oZD0mPGfDRF4C1VFxVZrg==,type:str]
sops:
  age:
    - recipient: age1xlgjxfxyshfagpcg25awdket4tp2xpy5m6xfewegllqqdq9utgtqgt2afg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZUUzRHlWZ2VqWVBtdVlj
        UGZxU1NNdFJLV2VLWkV6NmpkT0JHclE0YldVCnhDV1BkTEduaWk1aW11VWEzckNI
        dmE3Q1pIdnFHdHlzUVltanZvTUlZbjgKLS0tIEtybDdpL01FMlB1Q2h0cUJ0cmpv
        ZDVub2IrcmtqNElnVFY0eHdPY3VkQTAKgajA39Xt3eMmq5M2swmcX99eBxxTGG7p
        UEJ72YNMPJh5PMccSJQ6ZdL8RpUzC/v+4QSFO/elInJpL/HWR5YFNA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2025-11-09T11:00:57Z'
  mac: ENC[AES256_GCM,data:fNVn+7WeoKYHyZnttHwiMXb/1mGzElQbkaqPNl6/L1o973RnkXstl6fRUD4orFYD6Q6ckyuF40gF6VqDg9SleV5jKv9aRAFp09+CqPFlxzXSpuQvGkMnJ4cy8EJtvaFyrzQh0hlLfM4x3MQPcIEKE+raUDUwJWJbLSH1KWtMU4A=,iv:LqLzCphdI+j/SZjxzrrG39xIQq2nmXAvMcqi9mLPbbs=,tag:4LaP9St24bZJS35v1MTTtw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
