---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudflared
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
  namespace: cloudflared
type: Opaque
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:vELe1L2h2TIky4tZkAWDL+j5NzCkwxz/eyt54V4WAc3Rk76CHU5uP7jIvdlAm2xSY9f1mZJ+un/44w4x+zwqVvcT1X4VfgfSs2CGw6Y/ZS3ijIcG6H5n/oaG6aejEQz2OxS8NP3lQqyu3BX0Y+G2u1P01xRbhnoDFz7Ya79SpLLLu1kThnxbR6o8j0f43IXsxeP/9SagJELEZH/TqQYfkBvONOHi95wNFAB3D9gbNbusm2KP5PjUBQ==,iv:POmYgPO7dLaCyk++ovRYc9xCfmjnx8u66TUjydI1OOA=,tag:/1pItxcsij+seuznXiYoFw==,type:str]
sops:
  age:
    - recipient: age1xlgjxfxyshfagpcg25awdket4tp2xpy5m6xfewegllqqdq9utgtqgt2afg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtMEdnanFPM1dwV3RjaXlL
        bkprUGJ3WS94aHh1d3YwR1d6c3VWTGFoaWp3Cm00RmxQbVllZGEyZGczVTZodi9L
        V0MwL1ZCZ21wSXhhd3hTdmlqV0ZiUnMKLS0tIHhJTHVSZ2tLLzMvREptbjhOazU0
        VlhDdDl1Z1IydkpjMzErRkQwU1MrRjAKX+W4f9db2wHK8E4K3/8opbA0LlK9oRfS
        Yzsb0oq2V3nC3Hki9nLi1kqXM4M7ciypIYAHn/mdmmrd5rbxTNeCKg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2025-07-19T14:12:04Z'
  mac: ENC[AES256_GCM,data:y/usSKeYTD/8cOMJJ/VqEEmvwt2e3dNAoXjPMlClQEk6/MWhlau3gTwzshNboqT6LpdUgqFcx0bShciGEUka8lpjQ1RV4wUdWa+qs1ZWdy/HwHXKkEIdxOC0pVnjKzJOmF7O0+kluHInfH0fOTwbw3RF+pqGIzizpaBq5D90pJY=,iv:A6ezPTvulap4t/vp10LOxyrvxYpaa2/uR7QtmE6qX+s=,tag:pCceDRp08MoglwoXUY5f5Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
