---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
type: Opaque
stringData:
  api-token: ENC[AES256_GCM,data:fv/Pqx6NDAFyUzND8S0uYpz36RApmB5YR1Bk2sQp+zUKTZj4RaVTaQ==,iv:8/7ZBhB4QYx5/1/N+aQww9rbEvmhrCjIopRBcHbWY88=,tag:RXaYVIlxiOCdHqfcnHVyww==,type:str]
  email: ENC[AES256_GCM,data:VM+zeadviWP1fW7OmdHr1KzE,iv:L3Ql6kCSEWwhB9dmsQyh6llWn+w/wsH+uqfRd7+sQFQ=,tag:VyKvB/uoSAznfF17AIghFg==,type:str]
sops:
  age:
    - recipient: age1xlgjxfxyshfagpcg25awdket4tp2xpy5m6xfewegllqqdq9utgtqgt2afg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiT0UvVHpzZGJkcytzYXlO
        UUlsb3RHWmlIdnBTdm12WlZOcHdheGZZU1drCm1oMEMxS1FnWEJab3orcmtXeTJr
        SGhYWm5OTHIzMjRMTWM0Q01HZ2pabnMKLS0tIDhDQUowYkh4UHdMRzNIRVJUbDU2
        S2t1L0JnR3ZoeWpYaUhneVdHN0VKTXMKIT6Q8OKooK62j59TlXpBdsUA20kK82sL
        AeokK3DQyOmixcdBmvhTwgiU23JPNnhtoUbV6L3Ae5BY1hQ3S9j1Xw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2025-07-15T11:51:15Z'
  mac: ENC[AES256_GCM,data:CX4S4GDPXOWeHHujDSUXJSDmkWAIbU32YVujEFPttBJ3yq4iYyuvr97bynyDxMjHPth04lB95Mq/cXjpWZcUsE2lIlrTJ/O+PE5mOdllxWmwzwOQHXAN54QgKzDazRfOm487PFHgszhUTUmABdX3uwuQi7tPDatL1PN8v4H1suc=,iv:uuStmGXDzZID5/+3xYHAIv6pa3eSSomrFS4nq6xn1sE=,tag:rO9DJsvkU3Z9CoF92SXogA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
