---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: prometheus-operator
type: Opaque
stringData:
  grafana_password: ENC[AES256_GCM,data:oMh7ksVZ/6TW77D5kwz+CQ==,iv:NVBLA2uL9DUTpm3gdACnSBlgwZESXw65moG84oCi5DQ=,tag:jDN8MkpNL9wx1B2TsNdM5A==,type:str]
sops:
  age:
    - recipient: age1xlgjxfxyshfagpcg25awdket4tp2xpy5m6xfewegllqqdq9utgtqgt2afg
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTC91ODlEOUFDMFB6T1dK
        aC9oeWJEWkdsRXNJakFCTHpiMUY0aHB2N0I4CllwMGhMU3Nsek5BK1NSQy9HenFH
        YlltOXhha1lxaWlBNzZuRGFUc0g2ZDQKLS0tIExtckRIem1nSUlQSzhZeWduQzlh
        ZVo0S29OdmdnMGl0elFwNlV6UlF0U28K+caYIPRRZAP2hy27LtsskpkIZ2eXyyLv
        lDdqlE7V/jcBO0xmCiLovnWnlQKzeAHuUXaltwaTqAgvy71wB3rh/w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2025-07-16T10:37:38Z'
  mac: ENC[AES256_GCM,data:mj0n93oUpoEAgA/rhlOsQY6xc36wmHOiE3dDU/Lkn1aa5RvN+Q4I2Qzs1GeIjcYQtZJzlseSDYhtNaOMQVi5a++t0rgnwJiOv9giHu6lAkd/lDKh4MT6r0xl7qtuoQijJgLvdH+q7V4rre4f3gLQa5VP6DR9+49oYUvnA1qk5Qg=,iv:exPJSPD2ntgQouVRUnku1Vylqf2xbzi3dfjQBq8QnQ4=,tag:TjJ9yjbXP43UmfLRaStMxw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.10.2
