---
apiVersion: v1
kind: Namespace
metadata:
  name: netbox
---
apiVersion: v1
kind: Secret
metadata:
  name: netbox-secret
  namespace: netbox
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: 
  AWS_SECRET_ACCESS_KEY: 