# see https://github.com/frantathefranta/home-ops/blob/main/kubernetes/apps/default/netbox/app/helmrelease.yaml
# And chart options https://github.com/netbox-community/netbox-chart/tree/main/charts/netbox
apiVersion: v1
kind: Namespace
metadata:
  name: ${netbox_app_name}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netbox
  namespace: netbox
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: netbox
    namespace: flux-system
  values:
    commonAnnotations:
      reloader.stakater.com/auto: "true"
    image:
      # renovate: datasource=docker depName=ghcr.io/frantathefranta/netbox-custom
      registry: ghcr.io
      repository: netboxcommunity/netbox
      tag: v4.4.0 # {"$imagepolicy": "default:netbox:tag"}
    superuser:
      name: cloufish
      email: cloufisz@gmail.com
    admins:
      - ["cloufish", "cloufisz@gmail.com"]
    loginRequired: true
    timeZone: Europe/Warsaw
    dateFormat: "j. F, Y"
    shortDateFormat: "j.m.Y"
    timeFormat: "G:i"
    shortTimeFormat: "H:i:s"
    dateTimeFormat: "j. F, Y g:i a"
    shortDateTimeFormat: "j.m.Y H:i"
    storages: # TODO: Change this
      default:
        BACKEND: "storages.backends.s3.S3Storage" 
        OPTIONS:
          bucket_name: "netbox"
          endpoint_url: "https://rgw.franta.us"
          region_name: "us-east-1"
    existingSecret: netbox-secret
    replicaCount: 1
    resourcesPreset: "large"
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        interval: 1m
    postgresql:
      enabled: false
    valkey:
      enabled: false
    tasksDatabase:
      host: netbox-dragonfly.default.svc.cluster.local
      database: 0
      # existingSecretName: "netbox-secret"
      # existingSecretKey: "REDIS_PASSWORD"
    cachingDatabase:
      host: netbox-dragonfly.default.svc.cluster.local
      database: 1
      # existingSecretName: "netbox-secret"
      # existingSecretKey: "REDIS_PASSWORD"
    externalDatabase:
      host: netbox-pgbouncer.default.svc.cluster.local
      port: 5432
      database: netbox
      username: netbox
      existingSecretName: "netbox-pguser-netbox"
      existingSecretKey: "password"
      targetSessionAttrs: any
      disableServerSideCursors: true
      connMaxAge: 300
    email:
      server: smtp-relay.default.svc.cluster.local
      port: 25
      from: netbox@franta.dev
    persistence:
      enabled: false
    readinessProbe:
      enabled: true
      initialDelaySeconds: 60
      timeoutSeconds: 1
      periodSeconds: 10
      successThreshold: 1
    extraConfig:
      - secret:
          secretName: netbox-secret
    housekeeping:
      enabled: false
    worker:
      enabled: false
    plugins:
      - netbox_kea
      - netbox_topology_views
      - netbox_cable_labels
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: topology.kubernetes.io/zone
                  operator: NotIn
                  values:
                    - protactinium # FIXME: BIND VM runs on the same Proxmox node and it doesn't allow traffic from VF to bridge
  valuesFrom:
    - targetPath: storages.default.OPTIONS.access_key
      kind: Secret
      name: aws-s3-secret
      valuesKey: AWS_ACCESS_KEY_ID
    - targetPath: storages.default.OPTIONS.secret_key
      kind: Secret
      name: aws-s3-secret
      valuesKey: AWS_SECRET_ACCESS_KEY