# See https://github.com/drag0n141/home-ops/blob/master/kubernetes/apps/default/tandoor/app/helmrelease.yaml
# https://github.com/auricom/home-ops/blob/main/kubernetes/apps/default/tandoor/app/helmrelease.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: ${lidify_app_name}
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lidify
  namespace: ${lidify_app_name}
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    remediation:
      retries: 3
  values:
    controllers:
      ${lidify_app_name}:
        replicas: 1
        annotations:
          reloader.stakater.com/auto: 'true'
        containers:
          app:
            image:
              repository: thewicklowwolf/lidify
              tag: 0.2.3
            ports:
              - name: http
                containerPort: &httpPort 5000
            env:
              - name: mode
                value: LastFM
            envFrom:
              - secretRef:
                  name: lidify-secret
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 1Gi
    service:
      app:
        controller: ${lidify_app_name}
        type: ClusterIP
        ports:
          http:
            port: *httpPort
            protocol: TCP
    ingress:
      app:
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          kubernetes.io/tls-acme: 'true'
          nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
          nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        storageClass: longhorn-crypto-global
        accessMode: ReadWriteOnce
        size: 2Gi
        globalMounts:
          - path: /config
