---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata: 
  name: prowlarr
  namespace: prowlarr
spec:
  interval: 1m
  chart:
    spec: 
      chart: prowlarr
      version: '1.47.0'
      sourceRef: 
        kind: HelmRepository
        name: prowlarr 
        namespace: flux-system
      interval: 1m