---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname code-server # Change this
  namespace: flux-system
spec:
  targetNamespace: *appname
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 30m
  timeout: 5m
  prune: true 
  path: "./kubernetes/apps/programming/code-server/app" # Change this
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  postBuild:
    substitute:
      app_k8s_domain_name: k8s.cloufish.xyz
      default_k8s_cert_name: wildcard-k8s-cert-prod
      appName: *appname