---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata: 
  name: ${code_server_app_name}
  namespace: ${code_server_app_name}
spec:
  releaseName: ${code_server_app_name}
  interval: 5m
  chart:
    spec: 
      chart: ${code_server_app_name}
      sourceRef: 
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
      valuesFiles:
        - values.yml
      interval: 1m
---
apiVersion: v1
kind: Namespace
metadata:
  name: ${code_server_app_name}
  labels:
    name: ${code_server_app_name}
