---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bjw-s-helm-charts
  namespace: flux-system
spec:
  interval: 12h
  url: oci://ghcr.io/bjw-s/helm/
---
apiVersion: v1
kind: Namespace
metadata:
  name: ${code_server_app_name}
  labels:
    name: ${code_server_app_name}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata: 
  name: ${code_server_app_name}
  namespace: ${code_server_app_name}
spec:
  releaseName: ${code_server_app_name}
  interval: 5m
  chart:
    spec: 
      chart: ${code_server_app_name}
      sourceRef: 
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system
      valuesFiles:
        - values.yml
      interval: 1m

