---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrepository-source-v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: nicholaswilde 
  namespace: ${code_server_app_name}
spec:
  interval: 12h
  url: https://nicholaswilde.github.io/helm-charts/
---
apiVersion: v1
kind: Namespace
metadata:
  name: ${code_server_app_name}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata: 
  name: ${code_server_app_name}
  namespace: ${code_server_app_name}
spec:
  interval: 5m
  chart:
    spec: 
      chart: ${code_server_app_name}
      sourceRef: 
        kind: HelmRepository
        name: nicholaswilde
        namespace: ${code_server_app_name}
      interval: 1m
  values:
    image:
      repository: ghcr.io/linuxserver/code-server
      pullPolicy: IfNotPresent
      tag: "4.101.2"
    ingress: 
      enabled: true
      hosts: 
        - host: ${code_server_app_name}.${app_k8s_domain_name}
      tls: 
        - secretName: ${default_k8s_cert_name}

