---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bjw-s-charts
  namespace: ${code_server_app_name}
spec:
  interval: 12h
  url: https://bjw-s-labs.github.io/helm-charts/