apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &appname code-server
  namespace: *appname
spec:
  chart:
    spec:
      version: ">=1.0.0"
  values:
    ingress:
      hosts:
        - host: code-server.k8s.cloufish.xyz
          paths:
            - path: /
              pathType: ImplementationSpecific
