apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ${code_server_app_name}
  namespace: ${code_server_app_name}
spec:
  chart:
    spec:
      version: ">=1.0.0"
  values:
    ingress:
      hosts:
        - host: code-server.k8s.cloufish.xyz
          paths:
            - path: /
              pathType: ImplementationSpecific
