apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ${chatgpt-next} # This variable is defined inside clusters/production/apps.yaml
  namespace: ${chatgpt-next}
spec:
  chart:
    spec:
      version: ">=1.0.0"
  values:
    ingress:
      app:
        hosts:
          - host: "${chatgpt-next}.${app_k8s_domain_name}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "${chatgpt-next}.${app_k8s_domain_name}"
            secretName: ${chatgpt-next}-${default_k8s_cert_name}

