---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-controllers
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-secrets
    - name: infra-helm-repos
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/controllers
  prune: true
  wait: true
  postBuild:
    substitute:
      app_swarm_domain_name: swarm.cloufish.xyz
      app_k8s_domain_name: k8s.cloufish.xyz
      default_k8s_cert_name: k8s-cert-prod
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-configs
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-controllers
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/configs
  prune: true
  patches:
    - patch: |
        - op: replace
          path: /spec/acme/server
          value: https://acme-v02.api.letsencrypt.org/directory
      target:
        kind: ClusterIssuer
        name: letsencrypt-production
  postBuild:
    substitute:
      app_swarm_domain_name: swarm.cloufish.xyz
      app_k8s_domain_name: k8s.cloufish.xyz
      default_k8s_cert_name: k8s-cert-prod
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-secrets
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/secrets
  prune: true
  postBuild:
    substitute:
      app_swarm_domain_name: swarm.cloufish.xyz
      app_k8s_domain_name: k8s.cloufish.xyz
      default_k8s_cert_name: k8s-cert-prod
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-helm-repos
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/helm-repos
  prune: true
  postBuild:
    substitute:
      app_swarm_domain_name: swarm.cloufish.xyz
      app_k8s_domain_name: k8s.cloufish.xyz
      default_k8s_cert_name: k8s-cert-prod
  decryption:
    provider: sops
    secretRef:
      name: sops-age
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-certiticates
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-controllers
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/certificates
  prune: true
  postBuild:
    substitute:
      app_swarm_domain_name: swarm.cloufish.xyz
      app_k8s_domain_name: k8s.cloufish.xyz
      default_k8s_cert_name: k8s-cert-prod
  decryption:
    provider: sops
    secretRef:
      name: sops-age
