---
apiVersion: v1
kind: Namespace
metadata:
  name: k8up
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: k8up-io
  namespace: k8up
spec:
  interval: 24h
  url: https://k8up-io.github.io/k8up
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8up
  namespace: k8up
spec:
  interval: 30m
  chart:
    spec:
      chart: k8up
      version: "4.8.4" # If you consider upgrading, also upgrade k8up's CRD
      sourceRef:
        kind: HelmRepository
        name: k8up-io
        namespace: k8up
      interval: 12h

