apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ${dashy_app_name} # This variable is defined inside clusters/production/apps.yaml
  namespace: ${dashy_app_name}
spec:
  chart:
    spec:
      version: ">=1.0.0"
  values:
    ingress:
      app:
        hosts:
          - host: "${dashy_app_name}.${app_k8s_domain_name}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "${dashy_app_name}.${app_k8s_domain_name}"
            secretName: ${dashy_app_name}-${default_k8s_cert_name}

