apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: snapshot-default
  namespace: longhorn-system
spec:
  cron: "0 9 * * ?"
  task: "snapshot"
  groups:
  - default
  retain: 7
  concurrency: 1
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup-default
  namespace: longhorn-system
spec:
  cron: "0 0 1/5 * ?"
  task: "backup"
  groups:
  - default
  retain: 2
  concurrency: 1