apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-secret
    namespace: oauth2-proxy
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:uK/3VjILWl2aeKUyahSGfxbHS1vu+5kc3ZYDUrmVXEB1nggn7TOncunjLAUIgzNQDTtMx9Km7uxCyFbTpHuUph4Df2zBBVlF,iv:7VqAW8CLlfxycKy/Ng+B2HviNuRqnA967qvlLpAyu7w=,tag:ZAMyowAa2+JzsltLiaLuFw==,type:str]
    client-secret: ENC[AES256_GCM,data:rU4QDlls962wUrD0eD9iR2CreqZRScdHxoBhrysDYOepja8=,iv:H8U5nfbvgn7YPm8lUP9z0wdrLSAlDnpHFOAJzAeKXco=,tag:/Pk1pHDC7fuws31cL/RpgQ==,type:str]
    cookie-secret: ENC[AES256_GCM,data:/0KasGIqnPzoXDWl/wqI6sEJmNgx0OCPf+QhY2EjQt61gdofB6+swGVUA5Y=,iv:idU9Ig6/a/bAev9JHw2IhF6bQx2/z3CF1kZ6vdsv+yQ=,tag:0GBfJ4nmd0BWoocpwzh+wg==,type:str]
sops:
    age:
        - recipient: age1xlgjxfxyshfagpcg25awdket4tp2xpy5m6xfewegllqqdq9utgtqgt2afg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZkxwNVVxV0puR01SMzFG
            aUY1MjJtSkFuVHprZ01GcTcwL2JHbVBrUzIwCkdtVXdPTC9tMmVnMGgwSnk2Y0JM
            SnNpUnFPUU5iQ0RVa1hkZFlHMmwyVU0KLS0tIHdQSk56cE5CYjhiZC9QbE1CTzU5
            UnZpTlhONTVmRUhzS0R0WU9iSXA4Q2MK28QqQYfOFLbuNwnqAkBpJHw5dqum2Cdv
            glqbjiJHn7aaeSIBLi/0oeQQMPagJa3OMOXFI7327Jasjum65A8T4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-18T17:52:23Z"
    mac: ENC[AES256_GCM,data:3g9VG5IrvHeF1uMulI2mDzaSdDmFwKwRASYE0Ms6Lk2O5LTk0vpCQ8y5XWrOL6Mj6vHHxOWt67QOJlw5RDybLoOt5Rgqdk6mYM7FTPjulCVObCL5CyJMo+H5VhIJzEcZnj1vtzlkO30caURCaVPcrREmbSvWzf1bm1yVWNofY30=,iv:61Z120KuLmkoElBAXWrzwY9BFVWU7HMiWMzuWUUkLOg=,tag:QCFv1O1rBdKPDQQjKA8ciA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
