apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-secret
    namespace: oauth2-proxy
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:hMwkQETFTa0p3D2Ahwpu8ruVuPpnhsvMyBh39tI0udXvTOaW23BGrVm3plGc8YrCkq90ClhvvnTGe/l6KF4k6evlHjxJwHkZ,iv:fT0BBOwlL5qEEu6SQa1YqvHbphw3UiaTcz2F0/EcqTo=,tag:hWP3Qe24Ykm1cDzt3auKNg==,type:str]
    client-secret: ENC[AES256_GCM,data:8DCLpPMtRElfogUrM2SFi3votyNVw6fR2NgLU2qvhDumXZQ=,iv:0x0gtE3anoY9C2GCoEOewSoutybNajuheELZiYxUnZ0=,tag:yA81INdBvYaYA1ckXlLCTQ==,type:str]
    cookie-secret: ENC[AES256_GCM,data:eij6/sfP6L22fy4ZfyDb2De/Fo2wzz8jldWlLOQxIfblpVNuiMcDgM95vYA=,iv:HZWTyjplwr1UZXpGa1Anora4FSJHlzydhtmIU7ugZLc=,tag:mIyI22uRum7IcT0lPZN5ww==,type:str]
sops:
    age:
        - recipient: age1xlgjxfxyshfagpcg25awdket4tp2xpy5m6xfewegllqqdq9utgtqgt2afg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZWpNS09odE1YNEdPdjVl
            dkxEa2xkUnZIN083U3hOaXA4am5kS3VLRG1jCkpTUWgvcmoxOEl4YUJKVnljTUNN
            ZjROL09Na2NvNlpOblRTNy82OWNVd1EKLS0tIGxCY2dGaGltcnI2dE44djM1UXly
            bmFTZ2RwMUIrNnY3Ry9iUmVqTnJFVG8K6+7vMfNR0b2qdZzyE61TX+THN/XRqnrs
            tpTeeJ3DzBCZ1EptszJ5HLgj/GOp17mCAMn9p6AVjDJC4ihgSym9Sw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-18T18:11:36Z"
    mac: ENC[AES256_GCM,data:O077yPJ4pnrUIsKa0rbrdIWzL3XigF8JhuqbOZef1IWJyOs77TkyIm14j2eyKgehxu4zBDlPZFKMx6orZyTxK38B5w/EKGmNISGRPw2p4MJFrrneSoS3SFYfDSL6vMhoVIOkHyqfXtqi9SIGDOo4E8KIUGJcJ2LPcJCvwO85uhc=,iv:bXk0mg+OQku+AC8HAZsoBolJ7O/py0xVAabT4DzNKbA=,tag:d9xIW5wyqX3Kd0z8CYkRTQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
