---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bjw-s-charts
  namespace: ${home_assistant_app_name}
spec:
  interval: 12h
  url: https://bjw-s-labs.github.io/helm-charts/
---
apiVersion: v1
kind: Namespace
metadata:
  name: ${home_assistant_app_name}
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: ${home_assistant_app_name}
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.1.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: ${home_assistant_app_name}
  install:
    remediation:
      retries: 3
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 5050
        runAsGroup: 5050
        fsGroup: 5050
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      ${home_assistant_app_name}:
        annotations:
          reloader.stakater.com/auto: 'true'
        containers:
          app:
            image:
              repository: dpage/home_assistant4
              tag: 9.6
            env:
              TZ: Europe/Warsaw
#              home_assistant_CONFIG_AUTHENTICATION_SOURCES: "['oauth2']"
              home_assistant_CONFIG_CONSOLE_LOG_LEVEL: 10
              home_assistant_CONFIG_ENHANCED_COOKIE_PROTECTION: 'False'
            envFrom:
              - secretRef:
                  name: home_assistant-secret
            ports:
              - name: http
                containerPort: &httpPort 80
            resources:
              requests:
                cpu: 50m
                memory: 100Mi
              limits:
                memory: 500Mi
    service:
      app:
        controller: ${home_assistant_app_name}
        type: ClusterIP
        ports:
          http:
            port: *httpPort
            protocol: TCP
    ingress:
      app:
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          kubernetes.io/tls-acme: 'true'
          # nginx.ingress.kubernetes.io/ssl-redirect: 'true'
          # nginx.ingress.kubernetes.io/auth-url: https://oauth2-proxy.k8s.cloufish.xyz/oauth2/auth
          # nginx.ingress.kubernetes.io/auth-signin: https://oauth2-proxy.k8s.cloufish.xyz/oauth2/start?rd=$escaped_request_uri
          # nginx.ingress.kubernetes.io/auth-response-headers: Authorization
    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 5Gi
        globalMounts:
          - path: /var/lib/home_assistant
