apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-secret
    namespace: pgadmin
type: Opaque
stringData:
    PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:RythHYN/IxqtOafm96QjSOiE,iv:pgaK4cL8ooZ+HROmqtQcwJeijew4w2duzOS9bUE3bMg=,tag:mYb66UqQlaWMRuu4ko/tcg==,type:str]
    PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:OndieeapeovQnKr8Eyb5pfphPJXJJ5nV,iv:NCbs32jxSuFCdFXpLKDuqx9BOgyLoQaYhoRiA9/alN8=,tag:gxTkO6rxcrohSi70J1CSWA==,type:str]
sops:
    age:
        - recipient: age1xlgjxfxyshfagpcg25awdket4tp2xpy5m6xfewegllqqdq9utgtqgt2afg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlV3FkTzFSODJreXMxc1h1
            NlNDVmlCL0VpU1hRWjhYL3FMaUwzWTZQQ3dRClFtdXhTVmx4b1FDVkxUUDVYKzlo
            SldlbTRzZy93bnQrdXhBZk1KdGRSZ1UKLS0tIEZDbXBCWGJMUm91YnF0MEpuTjU2
            YXBHQTdxTE5UWUF2RW93ckhMaHFtc28K6x9p5ATs6Jdme0d+Iabo4JUf510u3dgr
            YOLP4GUlfCrxgJ+3TT0dEMutvSKpoys78CUh96OJNHnbQitY5pXpxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-06T17:48:17Z"
    mac: ENC[AES256_GCM,data:euFTfV0N/mgQVYlg4L2mrrdKC8QDkWQ4hgdTo9PzrHeRulPmgkA8lVN4Mtvh4EpRrEJy9zqWYsW102qoAHPr2BDf3ZIbL0COMfRKREhYiLodepCVS2qXpZOslQG9Ee2ZGMmKyU1+Rk6mEoHNa+AhkG4rXFmZo3oc7qA8wCK+Moc=,iv:lR8M2zxgcieLTXUW2fRrrjdlAa4yoSHMuWRow3lGqkM=,tag:Si26wG8Ia6slguRx9qjkYA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
