name: Perform basic linting 

on: 
    push:
        branches: 
        - "*"
    pull_request:

jobs:
  yamlint:
    name: yamlint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install yamllint
      shell: bash 
      run: | 
        pip install --user yamllint 
    
    - name: Run yamllint
      shell: bash 
      run: | 
        yamllint --format github

  markdownlint: 
    name: markdownlint
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout code 
      uses: actions/checkout@v4

    - name: Run markdownlint-cli
      uses: raven-actions/actionlint@v2.0.1
  
  actionlint: 
    name: actionlint
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout code 
      uses: actions/checkout@v4
    - name: Run actionlint
      uses: raven-actions/actionlint@v2.0.1

  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout code 
      uses: actions/checkout@v4
    - name: Run actionlint
      uses: ludeeus/action-shellcheck@master