---
name: validate-manifests
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: ['*']
    tags-ignore: ['*']
jobs:
  manifests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # So that it performs deep clone and can tell which files have changed
      - name: Setup yq
        uses: fluxcd/pkg/actions/yq@main
      - name: Setup kubeconform
        uses: fluxcd/pkg/actions/kubeconform@main
      - name: Setup kustomize
        uses: fluxcd/pkg/actions/kustomize@main
      - name: Validate manifests
        run: ./scripts/validate.sh
