---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: bjw-s-charts
  namespace: ${commafeed_app_name}
spec:
  interval: 12h
  url: https://bjw-s-labs.github.io/helm-charts/
---
apiVersion: v1
kind: Namespace
metadata:
  name: ${commafeed_app_name}
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: commafeed
  namespace: ${commafeed_app_name}
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.1.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: ${commafeed_app_name}
  install:
    remediation:
      retries: 3
  values:
    controllers:
      ${commafeed_app_name}:
        annotations:
          reloader.stakater.com/auto: 'true'
        containers:
          app:
            image:
              repository: athou/commafeed
              tag: master-postgresql-jvm
            env:
              - name: TZ 
                value: Europe/Warsaw
              - name: UID 
                value: 1000
              - name: GID
                value: "1000"
              - name: QUARKUS_DATASOURCE_JDBC_URL
                valueFrom:
                  secretKeyRef:
                    name: commafeed-postresql-cluster-app
                    key: jdbc-uri
              - name: QUARKUS_DATASOURCE_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: commafeed-postresql-cluster-app
                    key: username
              - name: QUARKUS_DATASOURCE_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: commafeed-postresql-cluster-app
                    key: password
            ports:
              - name: http
                containerPort: &httpPort 8082
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 1Gi
        pod:
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: ${commafeed_app_name}
        type: ClusterIP
        ports:
          http:
            port: *httpPort
            protocol: TCP
    ingress:
      app:
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          kubernetes.io/tls-acme: 'true'
          nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
          nginx.ingress.kubernetes.io/ssl-redirect: 'true'

